{"name": "test_login_1_error[data0]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '', 'pwd': '', 'expected': '请输入手机号'}"}], "start": 1569945387057, "stop": 1569945388411, "uuid": "e145111c-310b-4565-a94a-5a3109f589f3", "historyId": "9455ce2b003bf65fb75648c9c58cc9fc", "testCaseId": "0754122d22300ba419cd91efb872670c", "fullName": "test_cases.test_login.TestLogin#test_login_1_error", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-I3J3MGM"}, {"name": "thread", "value": "528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}